sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
services:
  - couchdb
before_script:
  # Show CouchDB version
  - curl http://localhost:5984
  # create admin account for testing (admin:secret)
  - curl -X PUT -d '"secret"' 'http://localhost:5984/_config/admins/admin'
  # Is it there?
  - curl --user admin:secret http://localhost:5984/_config/couch_httpd_auth/secret
script: 'echo "CouchDB sets no secret"'
