sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
services:
- couchdb
node_js:
- 4
before_install:
  # required for headless firefox / selenium test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
- npm prune
# create admin account for testing (admin:secret)
- curl -X PUT -d '"secret"' 'http://localhost:5984/_config/admins/admin'
- ls node_modules/.bin/
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
